spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    initialization-mode: always
  aop:
    proxy-target-class: true
logging:
  level:
    root: info
